FROM python:3.9
WORKDIR app
RUN apt update -y
RUN apt install build-essential cmake libopenblas-dev liblapack-dev libx11-dev libgtk-3-dev -y
RUN python3 -m pip install --upgrade pip
ARG SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
COPY inference/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY inference .
COPY db.py db.py
COPY utils.py utils.py
COPY storage storage
COPY exceptions exceptions
CMD ["sh", "download_artifacts_batch.sh"]