apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE
---
apiVersion: batch/v1
kind: Job
metadata:
  name: NAMESPACE-job
  namespace: NAMESPACE
  labels:
    app: trainer
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: app
                operator: In
                values:
                  - trainer
    metadata:
      name: NAMESPACE-job
    spec:
      containers:
        - image: CONTAINER_IMAGE
          imagePullPolicy: Always
          name: NAMESPACE
          command: ["python", "train.py"]
          env:
            - name: MLFLOW_TRACKING_URI
              value: MLFLOW_TRACKING_URI_VALUE
            - name: AWS_ACCESS_KEY_ID
              value: ACCESSKEY_AWS
            - name: AWS_SECRET_ACCESS_KEY
              value: SECRETKEY_AWS
            - name: AZURE_STORAGE_ACCESS_KEY
              value: ACCESSKEY_AZURE
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: SECRETKEY_AZURE
            - name: MONGO_URL
              value: MONGOURL
            - name: DB_NAME
              value: DBNAME
            - name: EXP_ID
              value: EXP_ID_VALUE
            - name: USERNAME
              value: USERNAME_VALUE
            - name: POSTGRES_URL
              value: POSTGRES_URL_VALUE
          resources:
            requests:
              memory: "MIN_MEMORY"
              cpu: "MIN_CPU"
            limits:
              memory: "MAX_MEMORY"
              cpu: "MAX_CPU"
      restartPolicy: Never

---